### ISSUE TITLE
strategy for memory limits

### ISSUE THREAD

**Issue by kbroughton** [tobilg/docker-mongodb-marathon#2]
Hi, nice work.
I'm running mongodb on marathon/mesos.  Our main issue is that the process often dies as it exceeds any memory set in the marathon job.  We have 32 Gb servers and allocate 4Gb to mongo.  Usually we have 20Gb free when the 4Gb mongo is exceeded.  Is there a way to un-restrict the memory for a task?

oversubscription seems to be a possible mechanism, placing mongo as the only priority task and letting all others run as over-subscribed.  Have you tackled this?  What about if mongo exceeds 32Gb, can we spill to swap somehow?
https://mesosphere.com/blog/2015/08/26/turbocharging-your-mesos-cluster-with-oversubscription/

Hmm. Looks like it will have to wait till marathon catches up 
https://github.com/mesosphere/marathon/issues/2424

**Comment by tobilg** [comment]
As I understand there's no current way to support this, as Marathon has not yet implemented this feature set apparently.

**Comment by JohnOmernik** [comment]
So how are you currently handling this when running Mongo on Marathon?
