### ISSUE TITLE
ECS + AWS Route 53?

### ISSUE THREAD

**Issue by mautematico** [tobilg/docker-mongodb-marathon#5]
¡Hola!

I am trying to deploy a replica set on ECS (+route 53?); I am thinking about making a derivate of your image for that propouse. Would you kindly point me to some document about the node.js configuration app your'e using on it?

¡Gracias!

**Comment by tobilg** [comment]
Hi @mautematico,

sorry, there is no documentation of the app itself. It uses the Marathon API to trigger the task starts etc., but I guess that's not available on ECS. To be honest, I doubt that you can port the app to interface with ECS.

**Comment by mautematico** [comment]
Never used the Marathon API before, but I think some of my team leads may give me a hint.

¡Gracias!

**Comment by tobilg** [comment]
You cannot use Marathon of you're not using Mesos or DC/OS. I guess you can't use this project on ECS, as I said before.

Therefore closing the issue.
